/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package DataModel.GUI;

import DataModel.Classes.Address;
import DataModel.Classes.Landlord;
import DataModel.Classes.LandlordList;
import DataModel.Interfaces.IObserver;
import javax.swing.DefaultListModel;

/**
 *
 * @author Thomas
 */
public class MainWindow extends javax.swing.JFrame implements IObserver{

    private DefaultListModel landlordList;
    private LandlordList list;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        this.landlordList = new DefaultListModel();
        this.list = new LandlordList();
        this.refreshListModel();
        list.registerObserver(this);
        initComponents();
        this.testData();
    }
    
    private void refreshListModel(){
        this.landlordList.clear();
        for (Landlord currLandlord : this.list.getList()){
            this.landlordList.addElement(currLandlord.getFullname());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTab = new javax.swing.JTabbedPane();
        landlordTab = new javax.swing.JPanel();
        listPane = new javax.swing.JScrollPane();
        landlordListview = new javax.swing.JList();
        clearLandlordfitlerbtn = new javax.swing.JButton();
        landlordTitle = new javax.swing.JLabel();
        landlordFilterTitle = new javax.swing.JLabel();
        landlordNamelbl = new javax.swing.JLabel();
        landlordNameInp = new javax.swing.JTextField();
        NoProplbl = new javax.swing.JLabel();
        landlordPropInp = new javax.swing.JTextField();
        landlordAddresslbl = new javax.swing.JLabel();
        landlordAddressInp = new javax.swing.JTextField();
        landlordEmaillbl = new javax.swing.JLabel();
        landlordEmailInp = new javax.swing.JTextField();
        landlordFilterbtn = new javax.swing.JButton();
        landlordTitle2 = new javax.swing.JLabel();
        llforenamelbl = new javax.swing.JLabel();
        llSurnamelbl = new javax.swing.JLabel();
        llAddresslbl = new javax.swing.JLabel();
        llCitylbl = new javax.swing.JLabel();
        llCountylbl = new javax.swing.JLabel();
        llPostcodelbl = new javax.swing.JLabel();
        llForenametxt = new javax.swing.JTextField();
        llSurnametxt = new javax.swing.JTextField();
        llAddresstxt = new javax.swing.JTextField();
        llCitytxt = new javax.swing.JTextField();
        llCountytxt = new javax.swing.JTextField();
        llPostcodetxt = new javax.swing.JTextField();
        SaveLandlordChangesbtn = new javax.swing.JButton();
        AddnewLandlordbtn = new javax.swing.JButton();
        llEmailAddresstxt = new javax.swing.JTextField();
        llEmailAddresslbl = new javax.swing.JLabel();
        deleteLandlordbtn = new javax.swing.JButton();
        tenantsTab = new javax.swing.JPanel();
        enquiriesTab = new javax.swing.JPanel();
        repairsTab = new javax.swing.JPanel();
        propertiesTab = new javax.swing.JPanel();
        landlordEmaillbl1 = new javax.swing.JLabel();
        landlordEmailInp1 = new javax.swing.JTextField();
        landlordAddresslbl1 = new javax.swing.JLabel();
        landlordAddressInp1 = new javax.swing.JTextField();
        NoProplbl1 = new javax.swing.JLabel();
        landlordPropInp1 = new javax.swing.JTextField();
        landlordNameInp1 = new javax.swing.JTextField();
        landlordNamelbl1 = new javax.swing.JLabel();
        landlordFilterTitle1 = new javax.swing.JLabel();
        landlordFilterbtn1 = new javax.swing.JButton();
        clearLandlordfitlerbtn1 = new javax.swing.JButton();
        landlordEmailInp2 = new javax.swing.JTextField();
        landlordFilterbtn2 = new javax.swing.JButton();
        landlordAddressInp2 = new javax.swing.JTextField();
        landlordEmaillbl2 = new javax.swing.JLabel();
        landlordPropInp2 = new javax.swing.JTextField();
        landlordAddresslbl2 = new javax.swing.JLabel();
        landlordNameInp2 = new javax.swing.JTextField();
        NoProplbl2 = new javax.swing.JLabel();
        landlordNamelbl2 = new javax.swing.JLabel();
        clearLandlordfitlerbtn2 = new javax.swing.JButton();
        listPane1 = new javax.swing.JScrollPane();
        landlordListview2 = new javax.swing.JList();
        landlordFilterTitle2 = new javax.swing.JLabel();
        landlordTitle3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        landlordTitle4 = new javax.swing.JLabel();
        landlordEmaillbl3 = new javax.swing.JLabel();
        landlordPropInp3 = new javax.swing.JTextField();
        landlordFilterbtn3 = new javax.swing.JButton();
        landlordAddressInp3 = new javax.swing.JTextField();
        landlordEmailInp3 = new javax.swing.JTextField();
        landlordNameInp3 = new javax.swing.JTextField();
        landlordAddresslbl3 = new javax.swing.JLabel();
        landlordNamelbl3 = new javax.swing.JLabel();
        NoProplbl3 = new javax.swing.JLabel();
        clearLandlordfitlerbtn3 = new javax.swing.JButton();
        landlordFilterTitle3 = new javax.swing.JLabel();
        landlordTitle5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        landlordListview.setModel(landlordList);
        landlordListview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                landlordListviewMouseClicked(evt);
            }
        });
        listPane.setViewportView(landlordListview);

        clearLandlordfitlerbtn.setText("Clear");
        clearLandlordfitlerbtn.setEnabled(false);

        landlordTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        landlordTitle.setText("Landlords");

        landlordFilterTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        landlordFilterTitle.setText("Filter Options");
        landlordFilterTitle.setEnabled(false);

        landlordNamelbl.setText("Landlord Name:");
        landlordNamelbl.setEnabled(false);

        landlordNameInp.setEnabled(false);
        landlordNameInp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordNameInpActionPerformed(evt);
            }
        });

        NoProplbl.setText("Number of properties:");
        NoProplbl.setEnabled(false);

        landlordPropInp.setEnabled(false);

        landlordAddresslbl.setText("Landlord Address:");
        landlordAddresslbl.setEnabled(false);

        landlordAddressInp.setEnabled(false);

        landlordEmaillbl.setText("Landlord Email address:");
        landlordEmaillbl.setEnabled(false);

        landlordEmailInp.setEnabled(false);

        landlordFilterbtn.setText("Filter List");
        landlordFilterbtn.setEnabled(false);
        landlordFilterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordFilterbtnActionPerformed(evt);
            }
        });

        landlordTitle2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        landlordTitle2.setText("Landlord Details");

        llforenamelbl.setText("Forname:");

        llSurnamelbl.setText("Surname:");

        llAddresslbl.setText("Address line 1:");

        llCitylbl.setText("City:");

        llCountylbl.setText("County:");

        llPostcodelbl.setText("Postcode:");

        llCountytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llCountytxtActionPerformed(evt);
            }
        });

        SaveLandlordChangesbtn.setText("Save Changes");
        SaveLandlordChangesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveLandlordChangesbtnActionPerformed(evt);
            }
        });

        AddnewLandlordbtn.setText("Add New Landlord");
        AddnewLandlordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddnewLandlordbtnActionPerformed(evt);
            }
        });

        llEmailAddresslbl.setText("Email Address:");

        deleteLandlordbtn.setText("Delete Selected");
        deleteLandlordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLandlordbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout landlordTabLayout = new javax.swing.GroupLayout(landlordTab);
        landlordTab.setLayout(landlordTabLayout);
        landlordTabLayout.setHorizontalGroup(
            landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landlordTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(landlordNamelbl)
                    .addComponent(NoProplbl)
                    .addComponent(landlordAddresslbl)
                    .addComponent(landlordEmaillbl)
                    .addComponent(landlordFilterTitle)
                    .addGroup(landlordTabLayout.createSequentialGroup()
                        .addComponent(clearLandlordfitlerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(landlordFilterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(landlordTabLayout.createSequentialGroup()
                        .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(landlordEmailInp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(landlordAddressInp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(landlordPropInp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(landlordNameInp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(landlordTitle, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(landlordTabLayout.createSequentialGroup()
                                .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(llforenamelbl)
                                    .addComponent(landlordTitle2)
                                    .addComponent(llSurnamelbl)
                                    .addComponent(llEmailAddresslbl)
                                    .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(llEmailAddresstxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                        .addComponent(llForenametxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(llSurnametxt, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(44, 44, 44)
                                .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(llAddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(llCitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(llCountytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(llCitylbl)
                                    .addComponent(llAddresslbl)
                                    .addComponent(llCountylbl)
                                    .addComponent(llPostcodelbl)
                                    .addComponent(llPostcodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(landlordTabLayout.createSequentialGroup()
                                .addComponent(SaveLandlordChangesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddnewLandlordbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteLandlordbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(1435, Short.MAX_VALUE))
        );
        landlordTabLayout.setVerticalGroup(
            landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landlordTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(landlordTitle)
                    .addComponent(landlordTitle2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(landlordTabLayout.createSequentialGroup()
                        .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(llforenamelbl)
                            .addComponent(llAddresslbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(llForenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(llAddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(llSurnamelbl)
                            .addComponent(llCitylbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(llSurnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(llCitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SaveLandlordChangesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AddnewLandlordbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deleteLandlordbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(landlordTabLayout.createSequentialGroup()
                                .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(llCountylbl)
                                    .addComponent(llEmailAddresslbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(llCountytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(llEmailAddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(llPostcodelbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(llPostcodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))))
                    .addComponent(listPane, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordFilterTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordNamelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordNameInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoProplbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordPropInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordAddresslbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordAddressInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordEmaillbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordEmailInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(landlordTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearLandlordfitlerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(landlordFilterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        mainTab.addTab("Landlords", landlordTab);

        tenantsTab.setEnabled(false);

        javax.swing.GroupLayout tenantsTabLayout = new javax.swing.GroupLayout(tenantsTab);
        tenantsTab.setLayout(tenantsTabLayout);
        tenantsTabLayout.setHorizontalGroup(
            tenantsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2285, Short.MAX_VALUE)
        );
        tenantsTabLayout.setVerticalGroup(
            tenantsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );

        mainTab.addTab("Tenants", tenantsTab);

        enquiriesTab.setEnabled(false);

        javax.swing.GroupLayout enquiriesTabLayout = new javax.swing.GroupLayout(enquiriesTab);
        enquiriesTab.setLayout(enquiriesTabLayout);
        enquiriesTabLayout.setHorizontalGroup(
            enquiriesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2285, Short.MAX_VALUE)
        );
        enquiriesTabLayout.setVerticalGroup(
            enquiriesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );

        mainTab.addTab("Enquiries", enquiriesTab);

        repairsTab.setEnabled(false);

        javax.swing.GroupLayout repairsTabLayout = new javax.swing.GroupLayout(repairsTab);
        repairsTab.setLayout(repairsTabLayout);
        repairsTabLayout.setHorizontalGroup(
            repairsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2285, Short.MAX_VALUE)
        );
        repairsTabLayout.setVerticalGroup(
            repairsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );

        mainTab.addTab("Repairs", repairsTab);

        landlordEmaillbl1.setText("Landlord Email address:");
        landlordEmaillbl1.setEnabled(false);

        landlordEmailInp1.setEnabled(false);

        landlordAddresslbl1.setText("Landlord Address:");
        landlordAddresslbl1.setEnabled(false);

        landlordAddressInp1.setEnabled(false);

        NoProplbl1.setText("Number of properties:");
        NoProplbl1.setEnabled(false);

        landlordPropInp1.setEnabled(false);

        landlordNameInp1.setEnabled(false);
        landlordNameInp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordNameInp1ActionPerformed(evt);
            }
        });

        landlordNamelbl1.setText("Landlord Name:");
        landlordNamelbl1.setEnabled(false);

        landlordFilterTitle1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        landlordFilterTitle1.setText("Filter Options");
        landlordFilterTitle1.setEnabled(false);

        landlordFilterbtn1.setText("Filter List");
        landlordFilterbtn1.setEnabled(false);
        landlordFilterbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordFilterbtn1ActionPerformed(evt);
            }
        });

        clearLandlordfitlerbtn1.setText("Clear");
        clearLandlordfitlerbtn1.setEnabled(false);

        landlordEmailInp2.setEnabled(false);

        landlordFilterbtn2.setText("Filter List");
        landlordFilterbtn2.setEnabled(false);
        landlordFilterbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordFilterbtn2ActionPerformed(evt);
            }
        });

        landlordAddressInp2.setEnabled(false);

        landlordEmaillbl2.setText("Landlord Email address:");
        landlordEmaillbl2.setEnabled(false);

        landlordPropInp2.setEnabled(false);

        landlordAddresslbl2.setText("Landlord Address:");
        landlordAddresslbl2.setEnabled(false);

        landlordNameInp2.setEnabled(false);
        landlordNameInp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordNameInp2ActionPerformed(evt);
            }
        });

        NoProplbl2.setText("Number of properties:");
        NoProplbl2.setEnabled(false);

        landlordNamelbl2.setText("Landlord Name:");
        landlordNamelbl2.setEnabled(false);

        clearLandlordfitlerbtn2.setText("Clear");
        clearLandlordfitlerbtn2.setEnabled(false);

        landlordListview2.setModel(landlordList);
        landlordListview2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                landlordListview2MouseClicked(evt);
            }
        });
        listPane1.setViewportView(landlordListview2);

        landlordFilterTitle2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        landlordFilterTitle2.setText("Landlord filter options");
        landlordFilterTitle2.setEnabled(false);

        landlordTitle3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        landlordTitle3.setText("Landlords");

        landlordTitle4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        landlordTitle4.setText("Properties");

        landlordEmaillbl3.setText("Postcode:");
        landlordEmaillbl3.setEnabled(false);

        landlordPropInp3.setEnabled(false);

        landlordFilterbtn3.setText("Filter List");
        landlordFilterbtn3.setEnabled(false);
        landlordFilterbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordFilterbtn3ActionPerformed(evt);
            }
        });

        landlordAddressInp3.setEnabled(false);

        landlordEmailInp3.setEnabled(false);

        landlordNameInp3.setEnabled(false);
        landlordNameInp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordNameInp3ActionPerformed(evt);
            }
        });

        landlordAddresslbl3.setText("County:");
        landlordAddresslbl3.setEnabled(false);

        landlordNamelbl3.setText("Address line 1:");
        landlordNamelbl3.setEnabled(false);

        NoProplbl3.setText("City");
        NoProplbl3.setEnabled(false);

        clearLandlordfitlerbtn3.setText("Clear");
        clearLandlordfitlerbtn3.setEnabled(false);

        landlordFilterTitle3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        landlordFilterTitle3.setText("Property filter options");
        landlordFilterTitle3.setEnabled(false);

        landlordTitle5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        landlordTitle5.setText("Properties");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout propertiesTabLayout = new javax.swing.GroupLayout(propertiesTab);
        propertiesTab.setLayout(propertiesTabLayout);
        propertiesTabLayout.setHorizontalGroup(
            propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertiesTabLayout.createSequentialGroup()
                .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(propertiesTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(landlordTitle3))
                        .addGap(18, 18, 18)
                        .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(landlordTitle5)))
                    .addGroup(propertiesTabLayout.createSequentialGroup()
                        .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(propertiesTabLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(landlordFilterTitle2)
                                    .addComponent(NoProplbl2)
                                    .addComponent(landlordAddressInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(landlordPropInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(landlordAddresslbl2)
                                    .addComponent(landlordEmaillbl2)
                                    .addComponent(landlordNamelbl2)
                                    .addComponent(landlordNameInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, propertiesTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(landlordEmailInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(propertiesTabLayout.createSequentialGroup()
                                        .addComponent(clearLandlordfitlerbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(landlordFilterbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(landlordNameInp3)
                            .addComponent(landlordPropInp3)
                            .addGroup(propertiesTabLayout.createSequentialGroup()
                                .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(landlordNamelbl3)
                                    .addComponent(NoProplbl3)
                                    .addComponent(landlordFilterTitle3)
                                    .addComponent(landlordAddresslbl3)
                                    .addComponent(landlordEmaillbl3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(landlordAddressInp3)
                            .addComponent(landlordEmailInp3)
                            .addGroup(propertiesTabLayout.createSequentialGroup()
                                .addComponent(clearLandlordfitlerbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(landlordFilterbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(propertiesTabLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(landlordTitle4))
                    .addGroup(propertiesTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1166, Short.MAX_VALUE)
                .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(landlordNamelbl1)
                        .addComponent(landlordFilterTitle1)
                        .addComponent(NoProplbl1)
                        .addComponent(landlordAddresslbl1)
                        .addComponent(landlordAddressInp1)
                        .addComponent(landlordNameInp1)
                        .addComponent(landlordPropInp1)
                        .addComponent(landlordEmaillbl1)
                        .addComponent(landlordEmailInp1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(propertiesTabLayout.createSequentialGroup()
                        .addComponent(clearLandlordfitlerbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(landlordFilterbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(174, 174, 174))
        );
        propertiesTabLayout.setVerticalGroup(
            propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertiesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(propertiesTabLayout.createSequentialGroup()
                        .addComponent(landlordFilterTitle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(landlordNamelbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(landlordNameInp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NoProplbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(landlordPropInp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(landlordAddresslbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(landlordAddressInp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(landlordEmaillbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(landlordEmailInp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearLandlordfitlerbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(landlordFilterbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(propertiesTabLayout.createSequentialGroup()
                        .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(landlordTitle3)
                            .addComponent(landlordTitle5)
                            .addComponent(landlordTitle4))
                        .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(propertiesTabLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2)
                                    .addComponent(listPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)))
                            .addGroup(propertiesTabLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(propertiesTabLayout.createSequentialGroup()
                                .addComponent(landlordFilterTitle3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(landlordNamelbl3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(landlordNameInp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NoProplbl3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(landlordPropInp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(landlordAddresslbl3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(landlordAddressInp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(landlordEmaillbl3))
                            .addGroup(propertiesTabLayout.createSequentialGroup()
                                .addComponent(landlordFilterTitle2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(landlordNamelbl2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(landlordNameInp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NoProplbl2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(landlordPropInp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(landlordAddresslbl2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(landlordAddressInp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(landlordEmaillbl2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(propertiesTabLayout.createSequentialGroup()
                                .addComponent(landlordEmailInp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(clearLandlordfitlerbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(landlordFilterbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(propertiesTabLayout.createSequentialGroup()
                                .addComponent(landlordEmailInp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(propertiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(clearLandlordfitlerbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(landlordFilterbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(23, 23, 23))
        );

        mainTab.addTab("Properties", propertiesTab);

        jScrollPane1.setViewportView(mainTab);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void landlordFilterbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordFilterbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordFilterbtn1ActionPerformed

    private void landlordNameInp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordNameInp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordNameInp1ActionPerformed

    private void deleteLandlordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLandlordbtnActionPerformed
        this.deleteLandlord(this.list.getLandlordAt(this.landlordListview.getSelectedIndex()));
    }//GEN-LAST:event_deleteLandlordbtnActionPerformed

    private void AddnewLandlordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddnewLandlordbtnActionPerformed
        this.addLandlord();
    }//GEN-LAST:event_AddnewLandlordbtnActionPerformed

    private void SaveLandlordChangesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveLandlordChangesbtnActionPerformed
        this.saveChanges(this.landlordListview.getSelectedIndex());
    }//GEN-LAST:event_SaveLandlordChangesbtnActionPerformed

    private void llCountytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llCountytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_llCountytxtActionPerformed

    private void landlordFilterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordFilterbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordFilterbtnActionPerformed

    private void landlordNameInpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordNameInpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordNameInpActionPerformed

    private void landlordListviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_landlordListviewMouseClicked
        this.displayData(this.landlordListview.getSelectedIndex());
    }//GEN-LAST:event_landlordListviewMouseClicked

    private void landlordFilterbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordFilterbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordFilterbtn2ActionPerformed

    private void landlordNameInp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordNameInp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordNameInp2ActionPerformed

    private void landlordListview2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_landlordListview2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordListview2MouseClicked

    private void landlordFilterbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordFilterbtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordFilterbtn3ActionPerformed

    private void landlordNameInp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordNameInp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordNameInp3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    private void testData(){
        this.list.addLandlord(new Landlord("Thomas","Smith", 
                new Address("8 Wyndham Sqaure", "Plymouth", "Devon", "PL1 5EF"), "thomassmith@tshs.info"));
    }
    
    private void displayData(int index){
        Landlord tempLl = this.list.getLandlordAt(index);
        this.llAddresstxt.setText(tempLl.getAddress());
        this.llCitytxt.setText(tempLl.getCity());
        this.llCountytxt.setText(tempLl.getCounty());
        this.llForenametxt.setText(tempLl.getforename());
        this.llSurnametxt.setText(tempLl.getSurname());
        this.llPostcodetxt.setText(tempLl.getPostcode());
        this.llEmailAddresstxt.setText(tempLl.getEmail());
    }
    
    private void saveChanges(int index){
        this.list.getLandlordAt(index).setAddress(this.llAddresstxt.getText());
        this.list.getLandlordAt(index).setCity(this.llCitytxt.getText());
        this.list.getLandlordAt(index).setCounty(this.llCountytxt.getText());
        this.list.getLandlordAt(index).setEmail(this.llEmailAddresstxt.getText());
        this.list.getLandlordAt(index).setPostcode(this.llEmailAddresstxt.getText());
        this.list.getLandlordAt(index).setSurname(this.llSurnametxt.getText());
        this.list.getLandlordAt(index).setforename(this.llForenametxt.getText());
    }
    
    private void addLandlord(){
        Landlord tempLl = new Landlord();
        tempLl.setAddress(this.llAddresstxt.getText());
        tempLl.setCity(this.llCitytxt.getText());
        tempLl.setCounty(this.llCountytxt.getText());
        tempLl.setEmail(this.llEmailAddresstxt.getText());
        tempLl.setPostcode(this.llPostcodetxt.getText());
        tempLl.setSurname(this.llSurnametxt.getText());
        tempLl.setforename(this.llForenametxt.getText());
        this.list.addLandlord(tempLl);
    }
    
    private void deleteLandlord(Landlord togo){
        this.list.deleteLandlord(togo);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddnewLandlordbtn;
    private javax.swing.JLabel NoProplbl;
    private javax.swing.JLabel NoProplbl1;
    private javax.swing.JLabel NoProplbl2;
    private javax.swing.JLabel NoProplbl3;
    private javax.swing.JButton SaveLandlordChangesbtn;
    private javax.swing.JButton clearLandlordfitlerbtn;
    private javax.swing.JButton clearLandlordfitlerbtn1;
    private javax.swing.JButton clearLandlordfitlerbtn2;
    private javax.swing.JButton clearLandlordfitlerbtn3;
    private javax.swing.JButton deleteLandlordbtn;
    private javax.swing.JPanel enquiriesTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField landlordAddressInp;
    private javax.swing.JTextField landlordAddressInp1;
    private javax.swing.JTextField landlordAddressInp2;
    private javax.swing.JTextField landlordAddressInp3;
    private javax.swing.JLabel landlordAddresslbl;
    private javax.swing.JLabel landlordAddresslbl1;
    private javax.swing.JLabel landlordAddresslbl2;
    private javax.swing.JLabel landlordAddresslbl3;
    private javax.swing.JTextField landlordEmailInp;
    private javax.swing.JTextField landlordEmailInp1;
    private javax.swing.JTextField landlordEmailInp2;
    private javax.swing.JTextField landlordEmailInp3;
    private javax.swing.JLabel landlordEmaillbl;
    private javax.swing.JLabel landlordEmaillbl1;
    private javax.swing.JLabel landlordEmaillbl2;
    private javax.swing.JLabel landlordEmaillbl3;
    private javax.swing.JLabel landlordFilterTitle;
    private javax.swing.JLabel landlordFilterTitle1;
    private javax.swing.JLabel landlordFilterTitle2;
    private javax.swing.JLabel landlordFilterTitle3;
    private javax.swing.JButton landlordFilterbtn;
    private javax.swing.JButton landlordFilterbtn1;
    private javax.swing.JButton landlordFilterbtn2;
    private javax.swing.JButton landlordFilterbtn3;
    private javax.swing.JList landlordListview;
    private javax.swing.JList landlordListview2;
    private javax.swing.JTextField landlordNameInp;
    private javax.swing.JTextField landlordNameInp1;
    private javax.swing.JTextField landlordNameInp2;
    private javax.swing.JTextField landlordNameInp3;
    private javax.swing.JLabel landlordNamelbl;
    private javax.swing.JLabel landlordNamelbl1;
    private javax.swing.JLabel landlordNamelbl2;
    private javax.swing.JLabel landlordNamelbl3;
    private javax.swing.JTextField landlordPropInp;
    private javax.swing.JTextField landlordPropInp1;
    private javax.swing.JTextField landlordPropInp2;
    private javax.swing.JTextField landlordPropInp3;
    private javax.swing.JPanel landlordTab;
    private javax.swing.JLabel landlordTitle;
    private javax.swing.JLabel landlordTitle2;
    private javax.swing.JLabel landlordTitle3;
    private javax.swing.JLabel landlordTitle4;
    private javax.swing.JLabel landlordTitle5;
    private javax.swing.JScrollPane listPane;
    private javax.swing.JScrollPane listPane1;
    private javax.swing.JLabel llAddresslbl;
    private javax.swing.JTextField llAddresstxt;
    private javax.swing.JLabel llCitylbl;
    private javax.swing.JTextField llCitytxt;
    private javax.swing.JLabel llCountylbl;
    private javax.swing.JTextField llCountytxt;
    private javax.swing.JLabel llEmailAddresslbl;
    private javax.swing.JTextField llEmailAddresstxt;
    private javax.swing.JTextField llForenametxt;
    private javax.swing.JLabel llPostcodelbl;
    private javax.swing.JTextField llPostcodetxt;
    private javax.swing.JLabel llSurnamelbl;
    private javax.swing.JTextField llSurnametxt;
    private javax.swing.JLabel llforenamelbl;
    private javax.swing.JTabbedPane mainTab;
    private javax.swing.JPanel propertiesTab;
    private javax.swing.JPanel repairsTab;
    private javax.swing.JPanel tenantsTab;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
       this.refreshListModel();
    }
}
